[Service]
WorkingDirectory=/root/telegram-bot/current
EnvironmentFile=
EnvironmentFile=/root/telegram-bot/current/.env
ExecStart=
ExecStart=/root/telegram-bot/venv-teamseek/bin/python3 /root/telegram-bot/current/src/bot.py
